"""Descriptive analysis of lab JSONL. No policy or rules code belongs here."""
import argparse
import collections
import json
import math
import statistics
import sys

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("files", nargs="*", help="JSONL files; defaults to stdin")
parser.add_argument("--pair", choices=["bot", "rules", "variant"])
parser.add_argument("--control")
parser.add_argument("--candidate")
parser.add_argument("--journeys", action="store_true", help="Compare full journeys by bot/budget and seed")
args = parser.parse_args()


def load(stream):
    for i, line in enumerate(stream, 1):
        r = json.loads(line)
        if args.journeys:
            if r.get("outcome") not in ["win", "loss", "timeout"] or not all(k in r for k in ["seed", "bot", "budget", "hp", "planning", "decisions", "trace", "unusedEnergy", "generatorUnusedUpperBound"]):
                raise ValueError(f"Invalid journey record at line {i}")
            if r.get("progression", "static") not in ["static", "shield-aware"]:
                raise ValueError(f"Unknown progression at line {i}")
            if sum(d['engineCalls'] or 0 for d in r['decisions']) != r['planning']['engineCalls']:
                raise ValueError(f"Planner accounting mismatch at line {i}")
            yield r
            continue
        if r.get("version") != "lab-1" or r.get("outcome") not in ["win", "loss", "timeout"]:
            raise ValueError(f"Unsupported result at line {i}")
        if r["actions"] != len(r["trace"]) or sum(c["drawn"] for c in r["cards"].values()) != r["drawn"]:
            raise ValueError(f"Telemetry mismatch at line {i}")
        yield r


rows = []
for path in args.files:
    with open(path) as stream:
        rows.extend(load(stream))
if not args.files:
    rows = list(load(sys.stdin))
if not rows:
    parser.error("No results")


def quantiles(values):
    a = sorted(values)
    return "/".join(str(a[max(0, math.ceil(len(a)*p)-1)]) for p in [0, .25, .5, .75, .95, 1]) if a else "N/A"


def mean(values):
    return statistics.mean(values) if values else 0


if args.journeys:
    groups = collections.defaultdict(dict)
    for r in rows:
        progression = r.get('progression', 'static')
        arm = f"{r['bot']}/{r['budget']}" + (f"/{progression}" if progression != 'static' else '')
        if r['seed'] in groups[arm]:
            raise ValueError(f"Duplicate journey {arm}/{r['seed']}")
        groups[arm][r['seed']] = r
    print("# Paired journey experiment\n")
    print("HP means include losses at zero. Unlabelled progression is static; other progression policies are explicit arm suffixes. Routes and rewards may diverge after combat changes. Engine calls count speculative rules transitions, not wall time.\n")
    print("| Policy/budget | n | wins | win Wilson 95% | mean HP | actions min/Q1/median/Q3/p95/max | mean engine calls | incomplete decisions | unused energy | generator-unused upper bound |")
    print("|---|---:|---:|---|---:|---|---:|---:|---:|---:|")
    for arm, by_seed in sorted(groups.items()):
        rs = list(by_seed.values()); n = len(rs); wins = sum(r['outcome']=='win' for r in rs)
        p = wins/n; z = 1.96; den = 1+z*z/n
        center = (p+z*z/(2*n))/den
        margin = z*math.sqrt(p*(1-p)/n+z*z/(4*n*n))/den
        print(f"| {arm} | {n} | {wins} | {center-margin:.3f}–{center+margin:.3f} | {mean([r['hp'] for r in rs]):.2f} | {quantiles([len(r['trace']) for r in rs])} | {mean([r['planning']['engineCalls'] for r in rs]):.0f} | {sum(r['planning']['incompleteDecisions'] for r in rs)}/{sum(len(r['decisions']) for r in rs)} | {mean([r['unusedEnergy'] for r in rs]):.2f} | {mean([r['generatorUnusedUpperBound'] for r in rs]):.2f} |")
    print("\nGenerator-unused is min(turn energy generated by cards, energy left at end), summed over explicit ends. It is an upper bound, not causal waste. Incomplete means at least one root candidate did not finish all belief samples.\n")
    print(f"Timeouts: {sum(r['outcome']=='timeout' for r in rows)}.\n")
    for a, left in sorted(groups.items()):
        for b, right in sorted(groups.items()):
            if b <= a:
                continue
            seeds = sorted(left.keys() & right.keys())
            if not seeds:
                continue
            delta = [right[s]['hp']-left[s]['hp'] for s in seeds]
            margin = 1.96*statistics.stdev(delta)/math.sqrt(len(delta)) if len(delta)>1 else None
            interval = f"[{mean(delta)-margin:.2f}, {mean(delta)+margin:.2f}]" if margin is not None else "unavailable"
            only_a = [s for s in seeds if left[s]['outcome']=='win' and right[s]['outcome']!='win']
            only_b = [s for s in seeds if right[s]['outcome']=='win' and left[s]['outcome']!='win']
            discordant = len(only_a)+len(only_b)
            exact = min(1,2*sum(math.comb(discordant,i) for i in range(min(len(only_a),len(only_b))+1))/2**discordant) if discordant else 1
            print(f"## {a} -> {b}\n")
            print(f"{len(seeds)} pairs, {len(left)+len(right)-2*len(seeds)} unmatched records. Mean HP delta {mean(delta):.2f}, approximate paired 95% interval {interval}.")
            print(f"Control-only/candidate-only wins: {len(only_a)}/{len(only_b)}; exact paired sign-test p={exact:.4f}, exploratory and unadjusted for multiple comparisons.")
            print(f"Mean action delta {mean([len(right[s]['trace'])-len(left[s]['trace']) for s in seeds]):.2f}.")
            print(f"Control-only seeds: {only_a}. Candidate-only seeds: {only_b}.\n")
    sys.exit(0)


def key(r):
    c = r["config"]
    return (c["bot"], c["fixture"]["deckId"], c["fixture"]["variant"], c["encounterId"], c["rules"])


def advantage(r, h):
    # Attrition proxy, not a calibrated win probability. Summons can lower it.
    return h["hp"]/70 - h["enemyHp"]/max(1, r["history"][0]["enemyHp"])


print("# Autonomous laboratory measurements\n")
print(f"{len(rows)} fights. Outcomes: {dict(collections.Counter(r['outcome'] for r in rows))}.")
print("Solo deck-versus-encounter results. First-player advantage and PvP matchup rates are not applicable. All rates describe these policies and seeded fixtures, not human players.\n")
print("## Matchup cells\n")
print("| Bot/deck/variant/encounter/rules | n | wins | mean HP | turns min/Q1/median/Q3/p95/max |")
print("|---|---:|---:|---:|---|")
groups = collections.defaultdict(list)
for r in rows:
    groups[key(r)].append(r)
for k, rs in sorted(groups.items()):
    print(f"| {'/'.join(k)} | {len(rs)} | {sum(r['outcome']=='win' for r in rs)} | {mean([r['finalHealth'] for r in rs]):.2f} | {quantiles([r['turns'] for r in rs])} |")
print("\nUse `bun scripts/lab.ts analyze` for Wilson 95% intervals by cell. Seeds paired across cells are not independent replicates.\n")
print("## Participation, resources and interaction\n")
print(f"Non-game signals: {sum(r['nonGameSignal'] for r in rows)}/{len(rows)}. Definition: three consecutive pass-only turns, or loss by turn 2. Includes intentional passes; not a diagnosis.")
print(f"Repeated-state warnings: {sum(r['repeatedState'] for r in rows)}. Timeouts: {sum(r['outcome']=='timeout' for r in rows)}. Neither is proof of an infinite loop.")
print(f"Mean energy generated/spent/unused at explicit ends: {mean([r['generated'] for r in rows]):.2f}/{mean([r['spent'] for r in rows]):.2f}/{mean([r['unused'] for r in rows]):.2f}.")
print(f"Mean actual damage received/blocked: {mean([r['damageTaken'] for r in rows]):.2f}/{mean([r['blocked'] for r in rows]):.2f}.")
print(f"First outgoing damage min/Q1/median/Q3/p95/max: {quantiles([r['firstDamage'] for r in rows if r['firstDamage'] is not None])}.")
print(f"First enemy attack/drain: {quantiles([r['firstInteraction'] for r in rows if r['firstInteraction'] is not None])}.")
histories = [h for r in rows for h in r['history']]
print(f"Mean legal actions: {mean([h['legal'] for h in histories]):.2f}. Decisions with more than one legal action: {sum(h['legal']>1 for h in histories)}/{len(histories)}. Legal diversity does not establish competitive action diversity.")
print(f"Hand cards unaffordable or without targets per decision: {mean([h['hand']-h['playable'] for h in histories]):.2f}. Forced-pass full turns: {sum(r['forcedPassTurns'] for r in rows)}.")

print("\n## Attrition and recovery proxies\n")
print("Advantage = party HP/70 minus remaining enemy HP/initial enemy HP. Ahead means >0.25; deficit means <-0.25. Ignores block, hand quality, energy and intents. Conditions on games still running at each turn; do not interpret as causal snowballing.")
for turn in [2, 4, 6]:
    for label, sign in [("ahead", 1), ("behind", -1)]:
        selected = [r for r in rows if (h := next((h for h in r['history'] if h['turn']==turn), None)) and advantage(r,h)*sign > .25]
        print(f"Turn {turn}, {label}: eventual wins {sum(r['outcome']=='win' for r in selected)}/{len(selected)}.")
deficits = [r for r in rows if min(advantage(r,h) for h in r['history']) < -.25]
recoveries = [r for r in deficits if r['outcome']=='win']
print(f"Wins after proxy deficit: {len(recoveries)}/{len(deficits)} deficit games. Low-health wins at <=20 HP: {sum(r['comeback'] for r in rows)}; low health alone is not a comeback.")
if recoveries:
    r = min(recoveries, key=lambda r:min(advantage(r,h) for h in r['history']))
    print(f"Largest recovered proxy deficit: {min(advantage(r,h) for h in r['history']):.3f}; config {json.dumps(r['config'])}.")

print("\n## Card observations\n")
print("Counts repeat per draw/play and per decision for held/playable. Inclusion is per game. Drawn/played win rates are selection-biased, not causal card strength.\n")
print("| Card | included games | draws | playable decisions | plays | discards | mean turn played | wins when played |")
print("|---|---:|---:|---:|---:|---:|---:|---:|")
for card in sorted({c for r in rows for c in r['cards']}):
    rs = [r for r in rows if card in r['cards']]
    total = collections.Counter()
    for r in rs:
        total.update(r['cards'][card])
    played = [r for r in rs if r['cards'][card]['played']]
    print(f"| {card} | {len(rs)} | {total['drawn']} | {total['playable']} | {total['played']} | {total['discarded']} | {total['turnTotal']/max(1,total['played']):.2f} | {sum(r['outcome']=='win' for r in played)}/{len(played)} |")

print("\n## Replay candidates\n")
ordered = sorted(rows, key=lambda r:r['turns'])
for label,r in [("short",ordered[0]),("typical",ordered[len(ordered)//2]),("long",ordered[-1]),("lowest health",min(rows,key=lambda r:r['finalHealth']))]:
    print(f"- {label}: {json.dumps(r['config'])}, {r['outcome']}, HP {r['finalHealth']}, turn {r['turns']}.")

if args.pair:
    if not args.control or not args.candidate:
        parser.error("--pair requires --control and --candidate")
    indices = {"bot":0,"variant":2,"rules":4}
    index = indices[args.pair]
    paired = collections.defaultdict(dict)
    for r in rows:
        k = list(key(r)); arm = k.pop(index)
        if arm not in [args.control,args.candidate]:
            continue
        k.extend([r['config']['seed'],r['config']['planningSeed'],r['config']['searchBudget'],r['config']['maxTurns'],r['config']['maxActions']])
        if arm in paired[tuple(k)]:
            raise ValueError("Duplicate matched configuration")
        paired[tuple(k)][arm] = r
    matches = [(p[args.control],p[args.candidate]) for p in paired.values() if args.control in p and args.candidate in p]
    if not matches:
        parser.error("No matched pairs")
    delta = [b['finalHealth']-a['finalHealth'] for a,b in matches]
    clusters = collections.defaultdict(list)
    for a,b in matches:
        clusters[a['config']['seed']].append(b['finalHealth']-a['finalHealth'])
    cluster_means = [mean(v) for v in clusters.values()]
    margin = 1.96*statistics.stdev(cluster_means)/math.sqrt(len(cluster_means)) if len(cluster_means)>1 else 0
    interval = f"[{mean(cluster_means)-margin:.3f}, {mean(cluster_means)+margin:.3f}]" if len(cluster_means)>1 else "unavailable with one seed"
    print("\n## Paired experiment\n")
    print(f"{args.control} -> {args.candidate}: {len(matches)} matched pairs; {len(paired)-len(matches)} unmatched configurations excluded.")
    print(f"Mean HP delta {mean(delta):.3f}; equally weighted seed-cluster mean {mean(cluster_means):.3f}, approximate 95% interval {interval} across {len(clusters)} seeds.")
    print(f"Mean turn delta {mean([b['turns']-a['turns'] for a,b in matches]):.3f}. Control-only wins {sum(a['outcome']=='win' and b['outcome']!='win' for a,b in matches)}; candidate-only wins {sum(b['outcome']=='win' and a['outcome']!='win' for a,b in matches)}.")
    print(f"HP better/tied/worse: {sum(x>0 for x in delta)}/{sum(x==0 for x in delta)}/{sum(x<0 for x in delta)}.")
